export {
  getCompanyBySlug,
  getCompanyDevelopedGames,
  getCompanyPublishedGames,
  getFeaturedCompanies,
  getFranchiseBySlug,
  getFranchiseGames,
  getFranchisesDirectory,
  getGameBySlug,
  getGamesDirectory,
  getGenres,
  getPlatforms,
  getRecentlyReleasedGameCards,
  getRecentlyReleasedGames,
  getRuleBasedRecommendations,
  resolveGameReference,
  searchGames,
  getTopRatedGameCards,
  getTopRatedGames,
  getUpcomingGameCards,
  getUpcomingGames,
  hasIgdbCredentials,
  isIgdbConfigError,
  isIgdbUpstreamError,
  sanitizeFranchiseSlug,
  sanitizeLimit,
  sanitizeSortMode,
} from "./client";

export type {
  DirectoryItem,
  FranchiseGame,
  GameCardData,
  GameSortMode,
  IgdbGame,
} from "./types";
