export {
  getCompanyBySlug,
  getCompanyDevelopedGames,
  getCompanyPublishedGames,
  getFeaturedCompanies,
  getFranchiseBySlug,
  getFranchiseGames,
  getFranchisesDirectory,
  getGameBySlug,
  getGamesDirectory,
  getGenres,
  getPlatforms,
  getRecentlyReleasedGameCards,
  getRecentlyReleasedGames,
  getRuleBasedRecommendations,
  resolveGameReference,
  searchGames,
  getTopRatedGameCards,
  getTopRatedGames,
  getUpcomingGameCards,
  getUpcomingGames,
  hasIgdbCredentials,
  isIgdbConfigError,
  isIgdbUpstreamError,
  sanitizeFranchiseSlug,
  sanitizeLimit,
  sanitizeSortMode,
  type FranchiseGame,
  type GameSortMode,
} from "./client";

export type { DirectoryItem, GameCardData, IgdbGame } from "./types";
